name: Simonwhitfield
favicon: null
layout_spectrum: 0.99593
typography_spectrum: 0.62531
title: SimonWhitfield
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0d0d'
    - '#3f3f3f'
    - '#bdbdbd'
    - '#686868'
    - '#f8f8f8'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
