name: Simonwhitfield
favicon: null
layout_spectrum: 0.99593
typography_spectrum: 0.8395938833709806
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#72b6ed'
    - '#b1e3bb'
    - '#0c1112'
    - '#0754b5'
    - '#ff4256'
  brandStrength: 0.75
  lightness: 0.980433649616316
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
