name: Simonwhitfield
favicon: null
layout_spectrum: 0.6655692821368575
typography_spectrum: 0.8395938833709806
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9104073711205274
  lightness: 0.980433649616316
  saturation: 0.5228276823181659
  rhythmicContrast: 0.8938580469693989
purpose: []
